[boot]
systemd=false
# WSL devpts has ptmxmode=000 makes /dev/ptmx unusable. forkpty() throws ENODEV.
# Remount /dev/pts with an openable ptmx. OOBE uses /dev/tty.
command=/bin/sh -c "mkdir -p /dev/pts; mount -t devpts devpts /dev/pts -o gid=5,mode=620,ptmxmode=666; /sbin/ldconfig"

[user]
default=root

[network]
generateResolvConf=true
generateHosts=true

[interop]
enabled=true
appendWindowsPath=true
